name: mdanalysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mdanalysis
  - mdanalysistests
  - pmda
  - dask
  - distributed
  - dask-jobqueue
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - flask
  - jinja2
  - requests
  - tqdm
  - pip
  - pip:
      - proxystore
      - proxystore-ex
      - google-crc32c
      - aiofiles
      - aioice
      - aiortc
      - aiosqlite
      - annotated-types
      - anyio
      - attrs
      - av
      - blinker
      - bokeh
      - certifi
      - cffi
      - charset-normalizer
      - click
      - cloudpickle
      - contourpy
      - cryptography
      - cycler
      - dask-expr
      - dnspython
      - docutils
      - fasteners
      - fonttools
      - fsspec
      - globus-sdk
      - griddataformats
      - h11
      - h2
      - hpack
      - httptools
      - hypercorn
      - hyperframe
      - hypothesis
      - idna
      - ifaddr
      - iniconfig
      - itsdangerous
      - joblib
      - kafka-python
      - kiwisolver
      - locket
      - lockfile
      - lz4
      - markupsafe
      - matplotlib-inline
      - mda-xdrlib
      - mmtf-python
      - mrcfile
      - msgpack
      - networkx
      - partd
      - pillow
      - pluggy
      - priority
      - pyarrow
      - pyarrow-hotfix
      - pycparser
      - pydantic
      - pydantic-core
      - pyee
      - pyjwt
      - pylibsrtp
      - pyopenssl
      - pyparsing
      - pystun3
      - pytest
      - python-daemon
      - python-dateutil
      - python-dotenv
      - pytz
      - pyyaml
      - quart
      - redis
      - sniffio
      - sortedcontainers
      - tblib
      - threadpoolctl
      - tomli-w
      - toolz
      - tzdata
      - urllib3
      - uvicorn
      - uvloop
      - watchfiles
      - websockets
      - werkzeug
      - wsproto
      - xyzservices
      - zict
